// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskBoard.Data;

#nullable disable

namespace TaskBoard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202192304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskBoard.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TaskBoard.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TaskBoard.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Assignee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78da9c4d-1100-4dcd-b60a-f411870cb470"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(608),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 1",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(610)
                        },
                        new
                        {
                            Id = new Guid("3e10ee5e-fddf-4c09-b6ab-b23bc10c12a6"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(619),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 2",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(619)
                        },
                        new
                        {
                            Id = new Guid("6888bcd4-9c27-42b8-bc04-e578149d99f2"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(640),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 3",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(641)
                        },
                        new
                        {
                            Id = new Guid("765d35c0-e891-4904-8b69-92ddf25ecae7"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(644),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 4",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(644)
                        },
                        new
                        {
                            Id = new Guid("d7003697-005d-4635-87af-9b1f225f5a86"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(647),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 5",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(648)
                        },
                        new
                        {
                            Id = new Guid("0928d264-e54a-4607-90a0-bccd02f20a2f"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(668),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 6",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(669)
                        },
                        new
                        {
                            Id = new Guid("ba7f8a37-7e28-494d-8954-c27f7ed39484"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(711),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 7",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(712)
                        },
                        new
                        {
                            Id = new Guid("828d2cbe-30f8-448c-97f5-a5269f78d1b2"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(715),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 8",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(716)
                        },
                        new
                        {
                            Id = new Guid("728adcc7-250c-4692-99fa-32f72248d49e"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(723),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 9",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(723)
                        },
                        new
                        {
                            Id = new Guid("31588230-8b91-4d51-9a48-6e7f025a0e4f"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(737),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 10",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(738)
                        },
                        new
                        {
                            Id = new Guid("7dca82f1-7117-4512-aa62-9f0b7213b97e"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(746),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 11",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(746)
                        },
                        new
                        {
                            Id = new Guid("34c5adb2-3cad-41bd-b749-f3e63910fa11"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(749),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 12",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(750)
                        },
                        new
                        {
                            Id = new Guid("24812b32-c11b-442b-a108-0e662ea4d109"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(753),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 13",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(753)
                        },
                        new
                        {
                            Id = new Guid("8d243d07-d499-49f4-81e1-975808b2f543"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(756),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 14",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(757)
                        },
                        new
                        {
                            Id = new Guid("2840da54-0edf-429e-ad84-b89fcccaa14d"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(760),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 15",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(760)
                        },
                        new
                        {
                            Id = new Guid("6aa411d4-5839-4b71-8978-c2ad61c1b0b1"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(763),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 16",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(764)
                        },
                        new
                        {
                            Id = new Guid("99978588-2bdd-4e57-a901-73071a232125"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(767),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 17",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(767)
                        },
                        new
                        {
                            Id = new Guid("6285a370-22db-479e-b5e2-9fe0d0fd8a5b"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(772),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 18",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(773)
                        },
                        new
                        {
                            Id = new Guid("3bf0cc9d-954a-4895-9592-d5e9786bf6d4"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(779),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 19",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(780)
                        },
                        new
                        {
                            Id = new Guid("f9dc9e64-a62e-4345-b488-bdb9f7fab6ec"),
                            CreatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(783),
                            Priority = 1,
                            Status = 0,
                            Title = "Seed Task 20",
                            UpdatedAt = new DateTime(2026, 2, 2, 19, 23, 3, 691, DateTimeKind.Utc).AddTicks(783)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
